### ISSUE TITLE
Strange results when using Map::Tube and Map::Tube::CLI with Map::Tube::Bielefeld

### ISSUE THREAD

**Issue by gwselke** [manwar/Map-Tube#13]
Running

`map-tube --map=Bielefeld --generate `

produces an image that seems to consist almost exclusively of one-way connections (which probably does not correspond to reality). According to this image, it should be possible, e.g., to go from Johannesstift to Kattenkamp (with one intermediate stop) but not the other way round.
However,

`map-tube --map=Bielefeld --start=Kattenkamp --end=Johannesstift`

does produce a route, viz., "Kattenkamp (Linie 1), Johannesstift (Linie 1)". This seems to me to be a contradiction between the image and the calculated route. (Note that the intermediate station is omitted, though.)

A further peculiarity is that, for the opposite direction,

`map-tube --map=Bielefeld --start=Johannesstift --end=Kattenkamp`

only "Johannesstift (Linie 1), Kattenkamp (Linie 1)" is output, again omitting the intermediate station (Deciusstraße).

Finally, the image contains three nodes (Rathaus, Jahnplatz, Hauptbahnhof) that are each connected to themselves. I am not quite sure what this would mean in reality.

I am not sure whether the cause lies within the map data (Map::Tube::Bielefeld and its XML file) or in the underlying Map::Tube source. But since the tests for Map::Tube::Bielefeld contain Test::Map::Tube and these tests pass, it seems that the issue may lie with Map::Tube.

**Comment by manwar** [comment]
@gwselke Happy to see you back. How are you? I hope and wish you are doing great.

To be honest with, I am not familiar with the map data for Bielefeld. I am getting confused with image and route.

I have the following questions, do you know the answer to them.

1) Does the command line tool gives the correct route as per the data?
2) If the answer to the question (1) is yes but not expected route then data is incorrect.
3) If the answer to the question (1) is no then it is bigger concern and more likely issue with Map::Tube.
4) Does the image generated respect the data?
5) If the answer to the question (4) is no then again it is the issue with map generation code,

If it boils down to the core Map::Tube then can you please try again previous version one by one, just to point out which previous version causing the issue.

I have written down the above points just so I don't miss when I dig deep later.

Thank you for your help in advance.

**Comment by gwselke** [comment]
Yes, glad to be back, Mohammad! And thank you very much indeed for your ultra-fast reply; this is amazing!
I am not familiar with the Bielefeld data either. The XML file does have some, IMHO, peculiarities; e.g., statioin Rathaus occurs three times in the collection of stations, with three different ids. Map::Tube does succeed in combining all three instances into one, apparently based on the station name (not its id), though -- which is nice. The documentation for the map data format used by Map::Tube does not explicitly say whether this is legal use, or whether each station should occur only once.

As for your questions: 
Here's the relevant section from the Bielefeld XML data:
```
    <station id="1-18" name="Johannesstift" line="1:18" link="1-19"/>
    <station id="1-19" name="Deciusstraße" line="1:19" link="1-20"/>
    <station id="1-20" name="Kattenkamp" line="1:20" link="1-21"/> 
```  
1. a) As indicated in my original note (2nd piece of code), the path from Johannesstift (id 1-19) to Kattenkamp (1-21) is **basically** correct. Unexpectedly, the intermediate station Deciusstraße (id 1-20) is not displayed by map-tube. I would expect something like "Johannesstift (Linie 1), Deciusstraße (Linie 1), Kattenkamp (Line 1)", but I get "Johannesstift (Linie 1), Kattenkamp (Linie 1)". I would regard this as incorrect (or "not quite correct" :-) )
1. b) Since the XML data explicitly say only that id 1-19 is linked to 1-20 (but not the other way round), and 1-20 to 1-21 (but not the other way round), I would expect that Map::Tube assumes this connection to be unidirectional (from Johannesstift through Deciusstraße to Kattenkamp, but not in the opposite direction). This is indeed what the image (map-tube ... --generate_map)  shows: a unidirectional arrow from Johannesstift to Deciusstraße and again from there to Kattenkamp. This would, in my understanding, imply that no path exists in the opposite direction (from Kattenkamp through Deciusstraße to Johannesstift). Still, that is what the first line of code in my original note produces.
Under these circumstances, I would expect to get no result for this direction, but I do get "Kattenkamp (Limie 1), Johannesstift (Linie 1)".
It seems that Map::Tube is giving me inconsistent results: either the image (--generate_map) incorrectly shows unidirectional links, or the routing algorithm incorrectly uses bidirectional routes.

2. For case a), I think map-tube gives unexpected (incorrect) results, as per the data. For case b), map-tube gives inconsistent results (--generate_map vs. routing algorithm). Which of the two is correct depends on how to properly interpret the XML data given above -- but they cannot both be correct at the same time.

3. a) I think the data correctly show that Deciusstraße is on the way, so I think Map::Tube should display it.
3. b) Inconsistent results (case b) are probably in the domain of Map::Tube. Alternatively, the use of unidirectional links could be outlawed -- but I think there may be cases where this is exactly is needed. (In any case, it should be documented, and probably tested by Test::Map::Tube.)

4. a) Yes, the image is correct with respect to the connections (in particular, but not limited to, the part from Johannisstraße to Kattenkamp).
4. b) As mentioned above, the XML data seem to imply unidirectional links (although the XML format documentation does not explicitly enforce this interpretation). So, yes, I would assume that the image is correct (but contradicting  the routing, as described unter 2 b) above).
4. c) The "self-connections" of Rathaus (id 1-14) and two other stations I would assume to be caused by improper XML data. However, Map::Tube sometimes seem to identify stations by their id (used for generating the arrows with --generate_map) and sometimes by their name (when collapsing multiple occurrences of the same name). In any case, arguably Map::Tube cannot be expected to cope with all kinds of troubled data. It might help, however, to state clearly, in the documentation of the XML/JSON formats, that each station should come up once only in the data -- if that is what you intended and implemented.

5. I would assume that the map-generating code is correct but that the interpretation of uni-directional links (if my understanding outlined above is correct) could be made more explicit. And same for multiply naming one and the same station. This, in particular, could also be checked in Test::Map::Tube (or in the validation routines incorporated into Map::Tube).

As far as documentation is concerned, I could offer my help in writing something up (if you considered this helpful -- I habe no ontention of being pushy).

Does that make things a bit clearer?
I have not yet had the time to run Bielefeld with earlier versions of Map::Tube -- that would take me a little time, but I could do it if it helps.
![Bielefeld](https://github.com/user-attachments/assets/fc2584ea-9e46-4c2b-a5ce-7c72fbb49b43)

**Comment by gwselke** [comment]
Just one more thought: could it be that the content of the Bielefeld XML data runs so contrary to the assumptions that Map::Tube makes (explicitly or implicitly) that the internal Map::Tube data structures will get messed up? But what concretely could that be?

**Comment by gwselke** [comment]
I have now checked this more rigorously, using a fake tube map for a fictitious town named Testmap. (Module included here -- not intended for release on CPAN, just for internal testing!)

This map contains five lines with four stations each, but each with different features: 

Line 1: unidirectional links, no station indices
Line 2: unidirectional links, with sttation indices
Line 3: bidirectional links, with station indices
Line 4: bidirectional links, with incomplete station indices
Line 5: unidirectional links, circular layout (last station connected to first one), with station indices.

The lines are intentionally pairwise disjoint. (That is not as outlandish as it may sound: the Kiev map is a real-world example for unconnected lines.)

The included test script highlights some unexpected results -- that is, unexpected by me.
There are several possible explanations:

a) My expectations are wrong. (I will be happy to learn more, then!)
b) Map::Tube is producing the wrong results. (In this case the test script may serve to identify coding issues.)
c) The underlying tube map data (XML file) are  illegal. To the best of my knowledge, the XML data do not contradict any published requirements, but possibly there are (undocumented) assumptions on the data. In this case, I would be grateful for learning about these assumptions, and I would also be happy to contribute to augmenting the existing documentation, and also to provide test cases that map authors could use in order to safeguard against mistakes.
[Map-Tube-Testmap-0.0.1.tar.gz](https://github.com/user-attachments/files/17967255/Map-Tube-Testmap-0.0.1.tar.gz)

**Comment by gwselke** [comment]
Testing now with Map::Tube 3.85 and my (admittedly and purposely pathological) Map::Tube::Testmap, which should help to isolate the (possible) issues.

All the issues seem to be resolved now, which is big progress -- great work, @manwar!

There seems to be only one issue left:
Unidirectional links are covered better now, but get_shortest_route( 'E street', 'G alley'  ) does not find a route, which should exist in this direction on Line 2. (Note that that the equivalent get_shortest_route( 'A street', 'C alley'  ) does find a route on Line 1. The only difference between Line 1 and Line 2 is that Line 2 contains station indices (e.g., line="2:2"), whereas Line 1 doesn't. So it seems that the indexing and the unidirectionality handling do not go well with each other.)

**Comment by manwar** [comment]
@gwselke I have released patch to deal with the issue.
Please try with Map::Tube v3.86 and Map::Tube::CLI v0.78.

I have added new --debug switch for testing purpose.

**Comment by gwselke** [comment]
Looks just beautiful now, @manwar!
The originally reported problem really seems to be caused by the map data. The Map::Tube module is not at fault.
